version: "3.9"
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx-original
    ports:
      - "1234:80"

  custom-app-nginx:
    build:
      context: .
      dockerfile: Dockerfile-topicos
    container_name: nginx-topicos
    ports:
      - "4321:80"