FROM node:14-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ["miniapi/package.json", "miniapi/package-lock.json*", "miniapi/npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3000
RUN chown -R node /usr/src/app
USER node
ENTRYPOINT ["node", "miniapi/index.js"]